In [63]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [64]:
dataset = pd.read_excel("dataset/flood dataset.xlsx")

In [65]:
dataset.isnull().any()

Temp           False
Humidity       False
Cloud Cover    False
ANNUAL         False
Jan-Feb        False
Mar-May        False
Jun-Sep        False
Oct-Dec        False
avgjune        False
sub            False
flood          False
dtype: bool

In [66]:
print(dataset.shape)
print(dataset.columns)
print(dataset.dtypes)
print(dataset.describe())


(115, 11)
Index(['Temp', 'Humidity', 'Cloud Cover', 'ANNUAL', 'Jan-Feb', 'Mar-May',
       'Jun-Sep', 'Oct-Dec', 'avgjune', 'sub', 'flood'],
      dtype='object')
Temp             int64
Humidity         int64
Cloud Cover      int64
ANNUAL         float64
Jan-Feb        float64
Mar-May        float64
Jun-Sep        float64
Oct-Dec        float64
avgjune        float64
sub            float64
flood            int64
dtype: object
             Temp    Humidity  Cloud Cover       ANNUAL     Jan-Feb  \
count  115.000000  115.000000   115.000000   115.000000  115.000000   
mean    29.600000   73.852174    36.286957  2925.487826   27.739130   
std      1.122341    2.947623     4.330158   422.112193   22.361032   
min     28.000000   70.000000    30.000000  2068.800000    0.300000   
25%     29.000000   71.000000    32.500000  2627.900000   10.250000   
50%     30.000000   74.000000    36.000000  2937.500000   20.500000   
75%     31.000000   76.000000    40.000000  3164.100000   41.600000   
ma

In [67]:
x = dataset[['Cloud Cover','ANNUAL','Jan-Feb','Mar-May','Jun-Sep']]


In [68]:
y = dataset.iloc[:,10].values

In [69]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=10)

In [11]:
!pip install xgboost


  Using cached xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.8/101.7 MB 2.4 MB/s eta 0:00:43
    --------------------------------------- 1.3/101.7 MB 2.6 MB/s eta 0:00:39
    --------------------------------------- 1.8/101.7 MB 2.4 MB/s eta 0:00:42
    --------------------------------------- 2.4/101.7 MB 2.4 MB/s eta 0:00:41
   - -------------------------------------- 3.1/101.7 MB 2.6 MB/s eta 0:00:38
   - -------------------------------------- 3.7/101.7 MB 2.6 MB/s eta 0:00:39
   - -------------------------------------- 4.2/101.7 MB 2.6 MB/s eta 0:00:38
   - -------------------------------------- 5.0/101.7 MB 2.7 MB/s eta 0:00:36
   -- ------------------------------------- 5.8/101.7 MB 2.8 MB/s eta 0:00:35
   -- ------------------------------------- 6.6/101.7 MB 2.8 MB/s eta 0:00:34
   -- --

In [70]:
from sklearn import tree
from sklearn import ensemble
from sklearn import neighbors
from xgboost import XGBClassifier

# Define models with controlled complexity

dtree = tree.DecisionTreeClassifier(
    
)

rf = ensemble.RandomForestClassifier()

knn = neighbors.KNeighborsClassifier()

xgb = XGBClassifier()


In [71]:
dtree.fit(x_train, y_train)
rf.fit(x_train, y_train)
knn.fit(x_train, y_train)
xgb.fit(x_train, y_train)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [72]:
p1  = dtree.predict(x_test)
p2 = rf.predict(x_test)
p3 = knn.predict(x_test)
p4 = xgb.predict(x_test)

In [73]:
from sklearn import metrics

print(metrics.accuracy_score(y_test,p1))
print(metrics.accuracy_score(y_test, p2))
print(metrics.accuracy_score(y_test, p3))
print(metrics.accuracy_score(y_test, p4))



0.9655172413793104
0.9655172413793104
1.0
0.9655172413793104


In [74]:
metrics.confusion_matrix(y_test,p4)


array([[26,  0],
       [ 1,  2]])

In [75]:
print(metrics.accuracy_score(y_test,p4))


0.9655172413793104


In [76]:
print(metrics.precision_score(y_test,p4))


1.0


In [77]:
print(metrics.recall_score(y_test,p4))


0.6666666666666666


In [78]:
# saving the file
from joblib import dump
dump(xgb,'floods.save')


['floods.save']

In [79]:
import joblib

model = joblib.load("floods.save")


In [80]:
model.predict([[45, 4000, 80, 600, 3000]])


array([1])

In [81]:
model.predict_proba([[45, 4000, 80, 600, 3000]])


array([[0.07515526, 0.92484474]], dtype=float32)

In [82]:
input_data = pd.DataFrame({
    'Cloud Cover': [45],
    'ANNUAL': [4000],
    'Jan-Feb': [80],
    'Mar-May': [600],
    'Jun-Sep': [3000]
})

print(input_data)


   Cloud Cover  ANNUAL  Jan-Feb  Mar-May  Jun-Sep
0           45    4000       80      600     3000


In [83]:
prediction = model.predict(input_data)[0]
probability = model.predict_proba(input_data)[0][1]

print("Prediction:", prediction)
print("Flood Probability:", probability)


Prediction: 1
Flood Probability: 0.92484474


In [84]:
import joblib
import pandas as pd

loaded_model = joblib.load("floods.save")

input_data = pd.DataFrame({
    'Cloud Cover': [45],
    'ANNUAL': [4000],
    'Jan-Feb': [80],
    'Mar-May': [600],
    'Jun-Sep': [3000]
})

print("Prediction from saved file:", loaded_model.predict(input_data))
print("Probability:", loaded_model.predict_proba(input_data))


Prediction from saved file: [1]
Probability: [[0.07515526 0.92484474]]
